//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by comp.rc
//
#define IDS_APP_TITLE                   1
#define IDC_12H                         10
#define IDC_24H                         11
#define IDC_ALARM_ON                    20
#define IDC_ON                          20
#define IDC_ALARM_OFF                   21
#define IDC_OFF                         21
#define IDD_DIALOG                      101
#define IDI_QP                          103
#define IDI_BELL                        105
#define IDC_TIME                        110
#define IDC_ALARM                       111
#define IDC_BELL                        1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
