/////////////////////////////////////////////////////////////////////
// Quantum Dining Philosophers RTK-32A port
// Copyright (c) 2002 Miro Samek, Palo Alto, CA. 
// All Rights Reserved.
/////////////////////////////////////////////////////////////////////
#ifndef port_h
#define port_h

#include "qf_rtk32a.h"
#include "qdpp.h"

#endif                                                      // port_h

