//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by reminder.rc
//
#define IDS_APP_TITLE                   1
#define IDD_DIALOG                      101
#define IDB_LOGO                        103
#define IDI_QP                          103
#define IDC_STATE                       1100
#define IDC_POLL                        1101
#define IDC_PROC                        1102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
