/******************************************************************** 
 * Quantum Dining Philosophers RTK32 port ("C+" version)
 * (c) Copyright 2001, Miro Samek, Palo Alto, CA
 * All Rights Reserved
 *******************************************************************/
#ifndef port_h
#define port_h

#include "qf_rtk32.h"
#include "qdpp.h"

#endif                                                   /* port_h */

