/////////////////////////////////////////////////////////////////////
// Quantum Dining Philosophers DOS port
// (c) Copyright 2001, Miro Samek, Palo Alto, CA
// All Rights Reserved
/////////////////////////////////////////////////////////////////////
#ifndef port_h
#define port_h

#include "qf_dos.h"
#include "qdpp.h"

#endif                                                      // port_h

